name: 🚀 Feature request
description: Suggest a new idea for Mix.
body:
  - type: textarea
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what you would like Mix to be able to do.

        Consider attaching something showing what you are imagining:
         * images
         * videos
         * code samples (remember to use code blocks)
    validations:
      required: true