name: Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_mix_repo:
    runs-on: ubuntu-latest
    name: Test Mix Repo
    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout remix_ui repo
        uses: actions/checkout@v2
        with:
          repository: conceptadev/remix_ui
          path: remix

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: cd main && flutter pub get

      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: main
        
      - run: cd main && flutter test
